version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/theweldersguide
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/deploy/before_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/deploy/after_install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/deploy/start_server.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/deploy/validate_service.sh
      timeout: 30
      runas: root
